# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10
script:
  - xcodebuild -project BaseAPI.xcodeproj -scheme BaseAPI -sdk iphonesimulator12.0 clean build | xcpretty
